import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "./providers";
import ReviewSection from "@/components/ReviewSection";
import ReasearchPaper from "@/components/ReasearchPaper";
import Gallery from "@/components/Gallery";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Book College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          <main className="min-h-[calc(100vh-250px)] mb-12">{children}</main>

          <Gallery />
          <ReasearchPaper />
          <ReviewSection />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
